# Generated by Django 3.0.3 on 2020-02-08 18:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corestats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combatant',
            fields=[
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='corestats.BaseModel')),
                ('current_hp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
            ],
        ),
    ]
