# Generated by Django 3.0.3 on 2020-03-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corestats', '0002_combatant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighters', models.ManyToManyField(to='corestats.Combatant')),
            ],
        ),
    ]
