# Generated by Django 3.0.3 on 2020-03-05 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corestats', '0003_fightstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightstat',
            name='fighter_limit',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
            preserve_default=False,
        ),
    ]
