# Generated by Django 3.0.3 on 2020-03-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corestats', '0004_fightstat_fighter_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightstat',
            name='fight_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
